name: Build

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_gh_pages:
        name: Build Website
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - uses: actions/cache@v2
              with:
                  path: ~/.pnpm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install Packages
              run: pnpm i
            - name: Build Static
              run: pnpm run build
            - name: Commit
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: "./build"
                  user_name: "JacobLinCool"
                  user_email: "jacoblincool@users.noreply.github.com"
                  publish_branch: "gh-pages"
